server:
  port: 8080
  http2:
    enabled: true
  address: 0.0.0.0

spring:
  profiles:
    active: default
  datasource:
    druid:
      url: jdbc:mysql://myblog.com:3306/myblog?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: helloroot
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: myblog.com
    password: root
    port: 6340
  cache:
    cache-names: redisCache
    type: redis
    redis:
      time-to-live: 5s
  aop:
    auto: true
  mvc:
    view:
      prefix: /
      suffix: .jsp
    pathmatch:
      use-suffix-pattern: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
mybatis:
  mapper-locations: ["/com/myblog/dao/*.xml"]
logging:
  level:
    root: error
  file:
    path: /data/logs