server:
  tomcat:
    basedir: ./logs/newblog

spring:
  config:
    import: classpath:application-common.yml
  datasource:
    url: jdbc:mysql://106.52.188.206:31044/myblog?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: ZtO1tkJMVV
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 106.52.188.206
    password: 0CVF5Dsh79
    port: 31857