server:
  tomcat:
    accesslog:
      directory: access
      enabled: true
      prefix: access_log
      suffix: .log
      max-days: 10
    basedir: ./tomcat

spring:
  config:
    import: classpath:application-common.yml
  datasource:
    url: jdbc:mysql://10.3.254.101:3306/myblog?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: ZtO1tkJMVV
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 10.3.255.90
    password: 0CVF5Dsh79
    port: 6379